export const CourseList = [
  {
    image: 'assets/images/courses/4by3/08.jpg',
    title: 'Building Scalable APIs with GraphQL',
    lectures: 18,
    completed: 6,
    enrolled: 125,
    status: 'Live',
    price: 250,
  },
  {
    image: 'assets/images/courses/4by3/10.jpg',
    title: 'Bootstrap 5 From Scratch',
    lectures: 0,
    completed: 0,
    enrolled: 145,
    status: 'Disable',
    price: 350,
  },
  {
    image: 'assets/images/courses/4by3/06.jpg',
    title: 'Angular – The Complete Guider',
    lectures: 37,
    completed: 20,
    enrolled: 145,
    status: 'Live',
    price: 652,
  },
  {
    image: 'assets/images/courses/4by3/02.jpg',
    title: 'Graphic Design Masterclass',
    lectures: 58,
    completed: 0,
    enrolled: 0,
    status: 'Applied',
    price: 245,
  },
  {
    image: 'assets/images/courses/4by3/04.jpg',
    title: 'Learn Invision',
    lectures: 16,
    completed: 0,
    enrolled: 0,
    status: 'Rejected',
    price: 365,
  },
  {
    image: 'assets/images/courses/4by3/03.jpg',
    title: 'Create a Design System in Figma',
    lectures: 25,
    completed: 0,
    enrolled: 0,
    status: 'Applied',
    price: 135,
  },
  {
    image: 'assets/images/courses/4by3/07.jpg',
    title: 'Deep Learning with React-Native',
    lectures: 18,
    completed: 10,
    enrolled: 186,
    status: 'Live',
    price: 256,
  },
  {
    image: 'assets/images/courses/4by3/11.jpg',
    title: 'Build Responsive Websites with HTML',
    lectures: 42,
    completed: 25,
    enrolled: 345,
    status: 'Live',
    price: 222,
  },
]
